// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.mjs";

function asciiBaseline() {
  return Stdlib_JsError.throwWithMessage("AccuracyProbe.res ascii line check: ascii baseline");
}

function unicodeColumn() {
  return Stdlib_JsError.throwWithMessage("AccuracyProbe.res unicode column check: 가나다");
}

function emojiColumn() {
  return Stdlib_JsError.throwWithMessage("AccuracyProbe.res emoji column check: 🌏 after emoji");
}

function multipleExpressions() {
  let combined = "first / second";
  return Stdlib_JsError.throwWithMessage("AccuracyProbe.res multi-line check: " + combined);
}

export {
  asciiBaseline,
  unicodeColumn,
  emojiColumn,
  multipleExpressions,
}
/* No side effect */
//# sourceMappingURL=AccuracyProbe.js.map
