// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SourceMapProbe from "./SourceMapProbe.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let match = React.useState(() => 0);
  let setCount = match[1];
  let sample_count = match[0];
  let sample = {
    title: "Vite + React",
    count: sample_count
  };
  let label = SourceMapProbe.renderLabel(sample);
  return JsxRuntime.jsx("main", {
    children: JsxRuntime.jsxs("section", {
      children: [
        JsxRuntime.jsx("p", {
          children: "ReScript source map probe",
          className: "eyebrow"
        }),
        JsxRuntime.jsx("h1", {
          children: "Breakpoints should land in .res files"
        }),
        JsxRuntime.jsx("p", {
          children: "Open DevTools, set breakpoints in App.res or SourceMapProbe.res, then click the buttons.",
          className: "summary"
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("span", {
            children: label
          }),
          className: "readout"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("button", {
              children: "Increment count",
              onClick: _event => setCount(current => current + 1 | 0)
            }),
            JsxRuntime.jsx("button", {
              children: "Throw ReScript exception",
              className: "danger",
              onClick: _event => SourceMapProbe.explode(sample)
            }),
            JsxRuntime.jsx("button", {
              children: "Throw JS Error",
              className: "danger",
              onClick: _event => SourceMapProbe.explodeJsError(sample)
            })
          ],
          className: "actions"
        })
      ],
      className: "panel"
    }),
    className: "app-shell"
  });
}

let make = App;

export {
  make,
}
/* react Not a pure module */
//# sourceMappingURL=App.js.map
