// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.mjs";

let crlfLabel = "CRLF source file";

function throwFromCrLf() {
  return Stdlib_JsError.throwWithMessage(crlfLabel + " should map to CrLfProbe.res");
}

export {
  crlfLabel,
  throwFromCrLf,
}
/* No side effect */
//# sourceMappingURL=CrLfProbe.js.map
