// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.mjs";

let DirectBrowserSourceMapError = /* @__PURE__ */Primitive_exceptions.create("DirectBrowserProbe.DirectBrowserSourceMapError");

function makeMessage() {
  return "Direct browser sourcemap sample from DirectBrowserProbe.res";
}

function throwFromDirectBrowser() {
  let message = "Direct browser sourcemap sample from DirectBrowserProbe.res";
  throw {
    RE_EXN_ID: DirectBrowserSourceMapError,
    _1: message,
    Error: new Error()
  };
}

export {
  DirectBrowserSourceMapError,
  makeMessage,
  throwFromDirectBrowser,
}
/* No side effect */
//# sourceMappingURL=DirectBrowserProbe.js.map
