// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

let root = document.querySelector("#root");

if (!(root == null)) {
  Client.createRoot(root).render(JsxRuntime.jsx(App.make, {}));
}

/* root Not a pure module */
//# sourceMappingURL=Main.js.map
