// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.mjs";

let NodeSourceMapError = /* @__PURE__ */Primitive_exceptions.create("NodeProbe.NodeSourceMapError");

function formatMessage(label) {
  return "노드 sourcemap 🌏 / " + label;
}

function crashFromNode() {
  let message = "노드 sourcemap 🌏 / stack trace should point at the original source";
  throw {
    RE_EXN_ID: NodeSourceMapError,
    _1: message,
    Error: new Error()
  };
}

crashFromNode();

export {
  NodeSourceMapError,
  formatMessage,
  crashFromNode,
}
/*  Not a pure module */
//# sourceMappingURL=NodeProbe.js.map
