// Generated by ReScript, PLEASE EDIT WITH CARE


function normalize(value) {
  return value + " / normalized";
}

function validate(value) {
  return value + " / validated";
}

function runPipe() {
  return globalThis.throwPipeMatchProbeErrorWithPrefix("pipe-input / normalized / validated", "PipeMatchProbe.res pipe crash: ");
}

function describe(result) {
  if (typeof result !== "object") {
    return globalThis.throwPipeMatchProbeError("PipeMatchProbe.res match crash: missing branch");
  }
  if (result.TAG === "PipeOk") {
    let decorated = "ok branch / " + result._0;
    return globalThis.throwPipeMatchProbeError("PipeMatchProbe.res match crash: " + decorated);
  }
  let decorated$1 = "failed branch / " + result._0;
  return globalThis.throwPipeMatchProbeError("PipeMatchProbe.res match crash: " + decorated$1);
}

function runMatchOk() {
  return describe({
    TAG: "PipeOk",
    _0: "ok-value"
  });
}

function runMatchMissing() {
  return describe("PipeMissing");
}

function runMatchFailed() {
  return describe({
    TAG: "PipeFailed",
    _0: "bad-value"
  });
}

export {
  normalize,
  validate,
  runPipe,
  describe,
  runMatchOk,
  runMatchMissing,
  runMatchFailed,
}
/* No side effect */
//# sourceMappingURL=PipeMatchProbe.js.map
