// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.mjs";

let BrowserSourceMapError = /* @__PURE__ */Primitive_exceptions.create("SourceMapProbe.BrowserSourceMapError");

function renderLabel(sample) {
  return "브라우저 sourcemap 🌏 / " + sample.title + " / count=" + String(sample.count);
}

function buildCrashMessage(sample) {
  let label = renderLabel(sample);
  return "Thrown from SourceMapProbe.res: " + label;
}

function explode(sample) {
  let message = buildCrashMessage(sample);
  throw {
    RE_EXN_ID: BrowserSourceMapError,
    _1: message,
    Error: new Error()
  };
}

function explodeJsError(sample) {
  let message = buildCrashMessage(sample);
  throw new Error(message);
}

export {
  BrowserSourceMapError,
  renderLabel,
  buildCrashMessage,
  explode,
  explodeJsError,
}
/* No side effect */
//# sourceMappingURL=SourceMapProbe.js.map
